//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3625
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Datos {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("dsConfiguracionDelElementoDeVerificacionAutomatico")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dsConfiguracionDelElementoDeVerificacionAutomatico : global::System.Data.DataSet {
        
        private ConfiguracionDelElementoDeVerificacionAutomaticoDataTable tableConfiguracionDelElementoDeVerificacionAutomatico;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public dsConfiguracionDelElementoDeVerificacionAutomatico() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected dsConfiguracionDelElementoDeVerificacionAutomatico(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["ConfiguracionDelElementoDeVerificacionAutomatico"] != null)) {
                    base.Tables.Add(new ConfiguracionDelElementoDeVerificacionAutomaticoDataTable(ds.Tables["ConfiguracionDelElementoDeVerificacionAutomatico"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public ConfiguracionDelElementoDeVerificacionAutomaticoDataTable ConfiguracionDelElementoDeVerificacionAutomatico {
            get {
                return this.tableConfiguracionDelElementoDeVerificacionAutomatico;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            dsConfiguracionDelElementoDeVerificacionAutomatico cln = ((dsConfiguracionDelElementoDeVerificacionAutomatico)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["ConfiguracionDelElementoDeVerificacionAutomatico"] != null)) {
                    base.Tables.Add(new ConfiguracionDelElementoDeVerificacionAutomaticoDataTable(ds.Tables["ConfiguracionDelElementoDeVerificacionAutomatico"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableConfiguracionDelElementoDeVerificacionAutomatico = ((ConfiguracionDelElementoDeVerificacionAutomaticoDataTable)(base.Tables["ConfiguracionDelElementoDeVerificacionAutomatico"]));
            if ((initTable == true)) {
                if ((this.tableConfiguracionDelElementoDeVerificacionAutomatico != null)) {
                    this.tableConfiguracionDelElementoDeVerificacionAutomatico.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "dsConfiguracionDelElementoDeVerificacionAutomatico";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsConfiguracionDelElementoDeVerificacionAutomatico.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableConfiguracionDelElementoDeVerificacionAutomatico = new ConfiguracionDelElementoDeVerificacionAutomaticoDataTable();
            base.Tables.Add(this.tableConfiguracionDelElementoDeVerificacionAutomatico);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeConfiguracionDelElementoDeVerificacionAutomatico() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            dsConfiguracionDelElementoDeVerificacionAutomatico ds = new dsConfiguracionDelElementoDeVerificacionAutomatico();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void ConfiguracionDelElementoDeVerificacionAutomaticoRowChangeEventHandler(object sender, ConfiguracionDelElementoDeVerificacionAutomaticoRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class ConfiguracionDelElementoDeVerificacionAutomaticoDataTable : global::System.Data.TypedTableBase<ConfiguracionDelElementoDeVerificacionAutomaticoRow> {
            
            private global::System.Data.DataColumn columnID;
            
            private global::System.Data.DataColumn columnTipoEV;
            
            private global::System.Data.DataColumn columnEntidadDestino;
            
            private global::System.Data.DataColumn columnAlgoritmoAplica;
            
            private global::System.Data.DataColumn columnNumMaxRepeticiones;
            
            private global::System.Data.DataColumn columnPeriodicidadDefecto;
            
            private global::System.Data.DataColumn columnNombreEnDestino;
            
            private global::System.Data.DataColumn columnConfirmado;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public ConfiguracionDelElementoDeVerificacionAutomaticoDataTable() {
                this.TableName = "ConfiguracionDelElementoDeVerificacionAutomatico";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal ConfiguracionDelElementoDeVerificacionAutomaticoDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected ConfiguracionDelElementoDeVerificacionAutomaticoDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn IDColumn {
                get {
                    return this.columnID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TipoEVColumn {
                get {
                    return this.columnTipoEV;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn EntidadDestinoColumn {
                get {
                    return this.columnEntidadDestino;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn AlgoritmoAplicaColumn {
                get {
                    return this.columnAlgoritmoAplica;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn NumMaxRepeticionesColumn {
                get {
                    return this.columnNumMaxRepeticiones;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PeriodicidadDefectoColumn {
                get {
                    return this.columnPeriodicidadDefecto;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn NombreEnDestinoColumn {
                get {
                    return this.columnNombreEnDestino;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ConfirmadoColumn {
                get {
                    return this.columnConfirmado;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public ConfiguracionDelElementoDeVerificacionAutomaticoRow this[int index] {
                get {
                    return ((ConfiguracionDelElementoDeVerificacionAutomaticoRow)(this.Rows[index]));
                }
            }
            
            public event ConfiguracionDelElementoDeVerificacionAutomaticoRowChangeEventHandler ConfiguracionDelElementoDeVerificacionAutomaticoRowChanging;
            
            public event ConfiguracionDelElementoDeVerificacionAutomaticoRowChangeEventHandler ConfiguracionDelElementoDeVerificacionAutomaticoRowChanged;
            
            public event ConfiguracionDelElementoDeVerificacionAutomaticoRowChangeEventHandler ConfiguracionDelElementoDeVerificacionAutomaticoRowDeleting;
            
            public event ConfiguracionDelElementoDeVerificacionAutomaticoRowChangeEventHandler ConfiguracionDelElementoDeVerificacionAutomaticoRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddConfiguracionDelElementoDeVerificacionAutomaticoRow(ConfiguracionDelElementoDeVerificacionAutomaticoRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public ConfiguracionDelElementoDeVerificacionAutomaticoRow AddConfiguracionDelElementoDeVerificacionAutomaticoRow(int ID, string TipoEV, int EntidadDestino, int AlgoritmoAplica, int NumMaxRepeticiones, int PeriodicidadDefecto, string NombreEnDestino, bool Confirmado) {
                ConfiguracionDelElementoDeVerificacionAutomaticoRow rowConfiguracionDelElementoDeVerificacionAutomaticoRow = ((ConfiguracionDelElementoDeVerificacionAutomaticoRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        ID,
                        TipoEV,
                        EntidadDestino,
                        AlgoritmoAplica,
                        NumMaxRepeticiones,
                        PeriodicidadDefecto,
                        NombreEnDestino,
                        Confirmado};
                rowConfiguracionDelElementoDeVerificacionAutomaticoRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowConfiguracionDelElementoDeVerificacionAutomaticoRow);
                return rowConfiguracionDelElementoDeVerificacionAutomaticoRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                ConfiguracionDelElementoDeVerificacionAutomaticoDataTable cln = ((ConfiguracionDelElementoDeVerificacionAutomaticoDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new ConfiguracionDelElementoDeVerificacionAutomaticoDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnID = base.Columns["ID"];
                this.columnTipoEV = base.Columns["TipoEV"];
                this.columnEntidadDestino = base.Columns["EntidadDestino"];
                this.columnAlgoritmoAplica = base.Columns["AlgoritmoAplica"];
                this.columnNumMaxRepeticiones = base.Columns["NumMaxRepeticiones"];
                this.columnPeriodicidadDefecto = base.Columns["PeriodicidadDefecto"];
                this.columnNombreEnDestino = base.Columns["NombreEnDestino"];
                this.columnConfirmado = base.Columns["Confirmado"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnID = new global::System.Data.DataColumn("ID", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnID);
                this.columnTipoEV = new global::System.Data.DataColumn("TipoEV", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTipoEV);
                this.columnEntidadDestino = new global::System.Data.DataColumn("EntidadDestino", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnEntidadDestino);
                this.columnAlgoritmoAplica = new global::System.Data.DataColumn("AlgoritmoAplica", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAlgoritmoAplica);
                this.columnNumMaxRepeticiones = new global::System.Data.DataColumn("NumMaxRepeticiones", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNumMaxRepeticiones);
                this.columnPeriodicidadDefecto = new global::System.Data.DataColumn("PeriodicidadDefecto", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPeriodicidadDefecto);
                this.columnNombreEnDestino = new global::System.Data.DataColumn("NombreEnDestino", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNombreEnDestino);
                this.columnConfirmado = new global::System.Data.DataColumn("Confirmado", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnConfirmado);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public ConfiguracionDelElementoDeVerificacionAutomaticoRow NewConfiguracionDelElementoDeVerificacionAutomaticoRow() {
                return ((ConfiguracionDelElementoDeVerificacionAutomaticoRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new ConfiguracionDelElementoDeVerificacionAutomaticoRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(ConfiguracionDelElementoDeVerificacionAutomaticoRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.ConfiguracionDelElementoDeVerificacionAutomaticoRowChanged != null)) {
                    this.ConfiguracionDelElementoDeVerificacionAutomaticoRowChanged(this, new ConfiguracionDelElementoDeVerificacionAutomaticoRowChangeEvent(((ConfiguracionDelElementoDeVerificacionAutomaticoRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.ConfiguracionDelElementoDeVerificacionAutomaticoRowChanging != null)) {
                    this.ConfiguracionDelElementoDeVerificacionAutomaticoRowChanging(this, new ConfiguracionDelElementoDeVerificacionAutomaticoRowChangeEvent(((ConfiguracionDelElementoDeVerificacionAutomaticoRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.ConfiguracionDelElementoDeVerificacionAutomaticoRowDeleted != null)) {
                    this.ConfiguracionDelElementoDeVerificacionAutomaticoRowDeleted(this, new ConfiguracionDelElementoDeVerificacionAutomaticoRowChangeEvent(((ConfiguracionDelElementoDeVerificacionAutomaticoRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.ConfiguracionDelElementoDeVerificacionAutomaticoRowDeleting != null)) {
                    this.ConfiguracionDelElementoDeVerificacionAutomaticoRowDeleting(this, new ConfiguracionDelElementoDeVerificacionAutomaticoRowChangeEvent(((ConfiguracionDelElementoDeVerificacionAutomaticoRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveConfiguracionDelElementoDeVerificacionAutomaticoRow(ConfiguracionDelElementoDeVerificacionAutomaticoRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dsConfiguracionDelElementoDeVerificacionAutomatico ds = new dsConfiguracionDelElementoDeVerificacionAutomatico();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "ConfiguracionDelElementoDeVerificacionAutomaticoDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class ConfiguracionDelElementoDeVerificacionAutomaticoRow : global::System.Data.DataRow {
            
            private ConfiguracionDelElementoDeVerificacionAutomaticoDataTable tableConfiguracionDelElementoDeVerificacionAutomatico;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal ConfiguracionDelElementoDeVerificacionAutomaticoRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableConfiguracionDelElementoDeVerificacionAutomatico = ((ConfiguracionDelElementoDeVerificacionAutomaticoDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int ID {
                get {
                    try {
                        return ((int)(this[this.tableConfiguracionDelElementoDeVerificacionAutomatico.IDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ID\' in table \'ConfiguracionDelElementoDeVerificacionAutomat" +
                                "ico\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableConfiguracionDelElementoDeVerificacionAutomatico.IDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string TipoEV {
                get {
                    try {
                        return ((string)(this[this.tableConfiguracionDelElementoDeVerificacionAutomatico.TipoEVColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TipoEV\' in table \'ConfiguracionDelElementoDeVerificacionAut" +
                                "omatico\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableConfiguracionDelElementoDeVerificacionAutomatico.TipoEVColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int EntidadDestino {
                get {
                    try {
                        return ((int)(this[this.tableConfiguracionDelElementoDeVerificacionAutomatico.EntidadDestinoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'EntidadDestino\' in table \'ConfiguracionDelElementoDeVerific" +
                                "acionAutomatico\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableConfiguracionDelElementoDeVerificacionAutomatico.EntidadDestinoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int AlgoritmoAplica {
                get {
                    try {
                        return ((int)(this[this.tableConfiguracionDelElementoDeVerificacionAutomatico.AlgoritmoAplicaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'AlgoritmoAplica\' in table \'ConfiguracionDelElementoDeVerifi" +
                                "cacionAutomatico\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableConfiguracionDelElementoDeVerificacionAutomatico.AlgoritmoAplicaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int NumMaxRepeticiones {
                get {
                    try {
                        return ((int)(this[this.tableConfiguracionDelElementoDeVerificacionAutomatico.NumMaxRepeticionesColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'NumMaxRepeticiones\' in table \'ConfiguracionDelElementoDeVer" +
                                "ificacionAutomatico\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableConfiguracionDelElementoDeVerificacionAutomatico.NumMaxRepeticionesColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int PeriodicidadDefecto {
                get {
                    try {
                        return ((int)(this[this.tableConfiguracionDelElementoDeVerificacionAutomatico.PeriodicidadDefectoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PeriodicidadDefecto\' in table \'ConfiguracionDelElementoDeVe" +
                                "rificacionAutomatico\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableConfiguracionDelElementoDeVerificacionAutomatico.PeriodicidadDefectoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string NombreEnDestino {
                get {
                    try {
                        return ((string)(this[this.tableConfiguracionDelElementoDeVerificacionAutomatico.NombreEnDestinoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'NombreEnDestino\' in table \'ConfiguracionDelElementoDeVerifi" +
                                "cacionAutomatico\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableConfiguracionDelElementoDeVerificacionAutomatico.NombreEnDestinoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Confirmado {
                get {
                    try {
                        return ((bool)(this[this.tableConfiguracionDelElementoDeVerificacionAutomatico.ConfirmadoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Confirmado\' in table \'ConfiguracionDelElementoDeVerificacio" +
                                "nAutomatico\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableConfiguracionDelElementoDeVerificacionAutomatico.ConfirmadoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsIDNull() {
                return this.IsNull(this.tableConfiguracionDelElementoDeVerificacionAutomatico.IDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetIDNull() {
                this[this.tableConfiguracionDelElementoDeVerificacionAutomatico.IDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTipoEVNull() {
                return this.IsNull(this.tableConfiguracionDelElementoDeVerificacionAutomatico.TipoEVColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTipoEVNull() {
                this[this.tableConfiguracionDelElementoDeVerificacionAutomatico.TipoEVColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsEntidadDestinoNull() {
                return this.IsNull(this.tableConfiguracionDelElementoDeVerificacionAutomatico.EntidadDestinoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetEntidadDestinoNull() {
                this[this.tableConfiguracionDelElementoDeVerificacionAutomatico.EntidadDestinoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsAlgoritmoAplicaNull() {
                return this.IsNull(this.tableConfiguracionDelElementoDeVerificacionAutomatico.AlgoritmoAplicaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetAlgoritmoAplicaNull() {
                this[this.tableConfiguracionDelElementoDeVerificacionAutomatico.AlgoritmoAplicaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsNumMaxRepeticionesNull() {
                return this.IsNull(this.tableConfiguracionDelElementoDeVerificacionAutomatico.NumMaxRepeticionesColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetNumMaxRepeticionesNull() {
                this[this.tableConfiguracionDelElementoDeVerificacionAutomatico.NumMaxRepeticionesColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPeriodicidadDefectoNull() {
                return this.IsNull(this.tableConfiguracionDelElementoDeVerificacionAutomatico.PeriodicidadDefectoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPeriodicidadDefectoNull() {
                this[this.tableConfiguracionDelElementoDeVerificacionAutomatico.PeriodicidadDefectoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsNombreEnDestinoNull() {
                return this.IsNull(this.tableConfiguracionDelElementoDeVerificacionAutomatico.NombreEnDestinoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetNombreEnDestinoNull() {
                this[this.tableConfiguracionDelElementoDeVerificacionAutomatico.NombreEnDestinoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsConfirmadoNull() {
                return this.IsNull(this.tableConfiguracionDelElementoDeVerificacionAutomatico.ConfirmadoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetConfirmadoNull() {
                this[this.tableConfiguracionDelElementoDeVerificacionAutomatico.ConfirmadoColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class ConfiguracionDelElementoDeVerificacionAutomaticoRowChangeEvent : global::System.EventArgs {
            
            private ConfiguracionDelElementoDeVerificacionAutomaticoRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public ConfiguracionDelElementoDeVerificacionAutomaticoRowChangeEvent(ConfiguracionDelElementoDeVerificacionAutomaticoRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public ConfiguracionDelElementoDeVerificacionAutomaticoRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591