//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3625
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Datos {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("dsRegistroDeEntidadDeVerificacionProcesado")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dsRegistroDeEntidadDeVerificacionProcesado : global::System.Data.DataSet {
        
        private RegistroDeEntidadDeVerificacionProcesadoDataTable tableRegistroDeEntidadDeVerificacionProcesado;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public dsRegistroDeEntidadDeVerificacionProcesado() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected dsRegistroDeEntidadDeVerificacionProcesado(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["RegistroDeEntidadDeVerificacionProcesado"] != null)) {
                    base.Tables.Add(new RegistroDeEntidadDeVerificacionProcesadoDataTable(ds.Tables["RegistroDeEntidadDeVerificacionProcesado"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public RegistroDeEntidadDeVerificacionProcesadoDataTable RegistroDeEntidadDeVerificacionProcesado {
            get {
                return this.tableRegistroDeEntidadDeVerificacionProcesado;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            dsRegistroDeEntidadDeVerificacionProcesado cln = ((dsRegistroDeEntidadDeVerificacionProcesado)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["RegistroDeEntidadDeVerificacionProcesado"] != null)) {
                    base.Tables.Add(new RegistroDeEntidadDeVerificacionProcesadoDataTable(ds.Tables["RegistroDeEntidadDeVerificacionProcesado"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableRegistroDeEntidadDeVerificacionProcesado = ((RegistroDeEntidadDeVerificacionProcesadoDataTable)(base.Tables["RegistroDeEntidadDeVerificacionProcesado"]));
            if ((initTable == true)) {
                if ((this.tableRegistroDeEntidadDeVerificacionProcesado != null)) {
                    this.tableRegistroDeEntidadDeVerificacionProcesado.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "dsRegistroDeEntidadDeVerificacionProcesado";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsRegistroDeEntidadDeVerificacionProcesado.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableRegistroDeEntidadDeVerificacionProcesado = new RegistroDeEntidadDeVerificacionProcesadoDataTable();
            base.Tables.Add(this.tableRegistroDeEntidadDeVerificacionProcesado);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeRegistroDeEntidadDeVerificacionProcesado() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            dsRegistroDeEntidadDeVerificacionProcesado ds = new dsRegistroDeEntidadDeVerificacionProcesado();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void RegistroDeEntidadDeVerificacionProcesadoRowChangeEventHandler(object sender, RegistroDeEntidadDeVerificacionProcesadoRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class RegistroDeEntidadDeVerificacionProcesadoDataTable : global::System.Data.TypedTableBase<RegistroDeEntidadDeVerificacionProcesadoRow> {
            
            private global::System.Data.DataColumn columnPep;
            
            private global::System.Data.DataColumn columnTipoEV;
            
            private global::System.Data.DataColumn columnFechaAlta;
            
            private global::System.Data.DataColumn columnID;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public RegistroDeEntidadDeVerificacionProcesadoDataTable() {
                this.TableName = "RegistroDeEntidadDeVerificacionProcesado";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal RegistroDeEntidadDeVerificacionProcesadoDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected RegistroDeEntidadDeVerificacionProcesadoDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PepColumn {
                get {
                    return this.columnPep;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TipoEVColumn {
                get {
                    return this.columnTipoEV;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn FechaAltaColumn {
                get {
                    return this.columnFechaAlta;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn IDColumn {
                get {
                    return this.columnID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public RegistroDeEntidadDeVerificacionProcesadoRow this[int index] {
                get {
                    return ((RegistroDeEntidadDeVerificacionProcesadoRow)(this.Rows[index]));
                }
            }
            
            public event RegistroDeEntidadDeVerificacionProcesadoRowChangeEventHandler RegistroDeEntidadDeVerificacionProcesadoRowChanging;
            
            public event RegistroDeEntidadDeVerificacionProcesadoRowChangeEventHandler RegistroDeEntidadDeVerificacionProcesadoRowChanged;
            
            public event RegistroDeEntidadDeVerificacionProcesadoRowChangeEventHandler RegistroDeEntidadDeVerificacionProcesadoRowDeleting;
            
            public event RegistroDeEntidadDeVerificacionProcesadoRowChangeEventHandler RegistroDeEntidadDeVerificacionProcesadoRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddRegistroDeEntidadDeVerificacionProcesadoRow(RegistroDeEntidadDeVerificacionProcesadoRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public RegistroDeEntidadDeVerificacionProcesadoRow AddRegistroDeEntidadDeVerificacionProcesadoRow(string Pep, string TipoEV, System.DateTime FechaAlta, int ID) {
                RegistroDeEntidadDeVerificacionProcesadoRow rowRegistroDeEntidadDeVerificacionProcesadoRow = ((RegistroDeEntidadDeVerificacionProcesadoRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        Pep,
                        TipoEV,
                        FechaAlta,
                        ID};
                rowRegistroDeEntidadDeVerificacionProcesadoRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowRegistroDeEntidadDeVerificacionProcesadoRow);
                return rowRegistroDeEntidadDeVerificacionProcesadoRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                RegistroDeEntidadDeVerificacionProcesadoDataTable cln = ((RegistroDeEntidadDeVerificacionProcesadoDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new RegistroDeEntidadDeVerificacionProcesadoDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnPep = base.Columns["Pep"];
                this.columnTipoEV = base.Columns["TipoEV"];
                this.columnFechaAlta = base.Columns["FechaAlta"];
                this.columnID = base.Columns["ID"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnPep = new global::System.Data.DataColumn("Pep", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPep);
                this.columnTipoEV = new global::System.Data.DataColumn("TipoEV", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTipoEV);
                this.columnFechaAlta = new global::System.Data.DataColumn("FechaAlta", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFechaAlta);
                this.columnID = new global::System.Data.DataColumn("ID", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnID);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public RegistroDeEntidadDeVerificacionProcesadoRow NewRegistroDeEntidadDeVerificacionProcesadoRow() {
                return ((RegistroDeEntidadDeVerificacionProcesadoRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new RegistroDeEntidadDeVerificacionProcesadoRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(RegistroDeEntidadDeVerificacionProcesadoRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.RegistroDeEntidadDeVerificacionProcesadoRowChanged != null)) {
                    this.RegistroDeEntidadDeVerificacionProcesadoRowChanged(this, new RegistroDeEntidadDeVerificacionProcesadoRowChangeEvent(((RegistroDeEntidadDeVerificacionProcesadoRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.RegistroDeEntidadDeVerificacionProcesadoRowChanging != null)) {
                    this.RegistroDeEntidadDeVerificacionProcesadoRowChanging(this, new RegistroDeEntidadDeVerificacionProcesadoRowChangeEvent(((RegistroDeEntidadDeVerificacionProcesadoRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.RegistroDeEntidadDeVerificacionProcesadoRowDeleted != null)) {
                    this.RegistroDeEntidadDeVerificacionProcesadoRowDeleted(this, new RegistroDeEntidadDeVerificacionProcesadoRowChangeEvent(((RegistroDeEntidadDeVerificacionProcesadoRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.RegistroDeEntidadDeVerificacionProcesadoRowDeleting != null)) {
                    this.RegistroDeEntidadDeVerificacionProcesadoRowDeleting(this, new RegistroDeEntidadDeVerificacionProcesadoRowChangeEvent(((RegistroDeEntidadDeVerificacionProcesadoRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveRegistroDeEntidadDeVerificacionProcesadoRow(RegistroDeEntidadDeVerificacionProcesadoRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dsRegistroDeEntidadDeVerificacionProcesado ds = new dsRegistroDeEntidadDeVerificacionProcesado();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "RegistroDeEntidadDeVerificacionProcesadoDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class RegistroDeEntidadDeVerificacionProcesadoRow : global::System.Data.DataRow {
            
            private RegistroDeEntidadDeVerificacionProcesadoDataTable tableRegistroDeEntidadDeVerificacionProcesado;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal RegistroDeEntidadDeVerificacionProcesadoRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableRegistroDeEntidadDeVerificacionProcesado = ((RegistroDeEntidadDeVerificacionProcesadoDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Pep {
                get {
                    try {
                        return ((string)(this[this.tableRegistroDeEntidadDeVerificacionProcesado.PepColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Pep\' in table \'RegistroDeEntidadDeVerificacionProcesado\' is" +
                                " DBNull.", e);
                    }
                }
                set {
                    this[this.tableRegistroDeEntidadDeVerificacionProcesado.PepColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string TipoEV {
                get {
                    try {
                        return ((string)(this[this.tableRegistroDeEntidadDeVerificacionProcesado.TipoEVColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TipoEV\' in table \'RegistroDeEntidadDeVerificacionProcesado\'" +
                                " is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRegistroDeEntidadDeVerificacionProcesado.TipoEVColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime FechaAlta {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableRegistroDeEntidadDeVerificacionProcesado.FechaAltaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'FechaAlta\' in table \'RegistroDeEntidadDeVerificacionProcesa" +
                                "do\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRegistroDeEntidadDeVerificacionProcesado.FechaAltaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int ID {
                get {
                    try {
                        return ((int)(this[this.tableRegistroDeEntidadDeVerificacionProcesado.IDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ID\' in table \'RegistroDeEntidadDeVerificacionProcesado\' is " +
                                "DBNull.", e);
                    }
                }
                set {
                    this[this.tableRegistroDeEntidadDeVerificacionProcesado.IDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPepNull() {
                return this.IsNull(this.tableRegistroDeEntidadDeVerificacionProcesado.PepColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPepNull() {
                this[this.tableRegistroDeEntidadDeVerificacionProcesado.PepColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTipoEVNull() {
                return this.IsNull(this.tableRegistroDeEntidadDeVerificacionProcesado.TipoEVColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTipoEVNull() {
                this[this.tableRegistroDeEntidadDeVerificacionProcesado.TipoEVColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsFechaAltaNull() {
                return this.IsNull(this.tableRegistroDeEntidadDeVerificacionProcesado.FechaAltaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetFechaAltaNull() {
                this[this.tableRegistroDeEntidadDeVerificacionProcesado.FechaAltaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsIDNull() {
                return this.IsNull(this.tableRegistroDeEntidadDeVerificacionProcesado.IDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetIDNull() {
                this[this.tableRegistroDeEntidadDeVerificacionProcesado.IDColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class RegistroDeEntidadDeVerificacionProcesadoRowChangeEvent : global::System.EventArgs {
            
            private RegistroDeEntidadDeVerificacionProcesadoRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public RegistroDeEntidadDeVerificacionProcesadoRowChangeEvent(RegistroDeEntidadDeVerificacionProcesadoRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public RegistroDeEntidadDeVerificacionProcesadoRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591